version: '3'

services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    environment:
      REDIS_URL: redis://redis:6379

  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      REDIS_URL: redis://redis:6379
      # GIN_MODE: release
    depends_on:
      - redis
