version: '3'

services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    environment:
      REDIS_URL: redis://redis:6379

  app:
    build: .
    ports:
      - "9001:9001"
    environment:
      REDIS_URL: redis://redis:6379
    depends_on:
      - redis
